import { User, Profile, Task, Category, Provider, Payment, Notification } from '@/types';

export const mockUsers: Record<string, User> = {
  customer1: {
    id: 'user_cust_101',
    name: 'Sarah Jenkins',
    email: 'sarah.j@example.com',
    role: 'CUSTOMER',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 234-5678',
    status: 'ACTIVE',
    createdAt: '2025-01-15T08:00:00Z',
  },
  provider1: {
    id: 'user_prov_202',
    name: 'Alex Rivera',
    email: 'alex.r@example.com',
    role: 'PROVIDER',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 876-5432',
    status: 'ACTIVE',
    createdAt: '2024-11-10T08:00:00Z',
  },
  admin1: {
    id: 'user_admin_303',
    name: 'Elena Rostova',
    email: 'elena.admin@taskhub.com',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 999-0000',
    status: 'ACTIVE',
    createdAt: '2024-01-01T08:00:00Z',
  },
};

export const mockCustomerProfile: Profile = {
  id: 'prof_cust_101',
  userId: 'user_cust_101',
  bio: 'Homeowner, tech enthusiast, looking for reliable professionals for home maintenance & design projects.',
  address: '742 Evergreen Terrace',
  city: 'Austin',
  state: 'TX',
  zipCode: '78701',
  country: 'United States',
  avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  rating: 4.9,
  reviewCount: 14,
  completedTasks: 18,
  createdAt: '2025-01-15T08:00:00Z',
};

export const mockCategories: Category[] = [
  {
    id: 'cat_home',
    name: 'Home Improvement',
    slug: 'home-improvement',
    description: 'Plumbing, electrical, assembly & repairs',
    icon: 'Wrench',
    taskCount: 142,
  },
  {
    id: 'cat_tech',
    name: 'Tech & IT Support',
    slug: 'tech-it-support',
    description: 'Web dev, hardware repair, network setup',
    icon: 'Laptop',
    taskCount: 98,
  },
  {
    id: 'cat_cleaning',
    name: 'Cleaning & Housekeeping',
    slug: 'cleaning-housekeeping',
    description: 'Deep cleaning, move-in/out, laundry',
    icon: 'Sparkles',
    taskCount: 215,
  },
  {
    id: 'cat_moving',
    name: 'Moving & Delivery',
    slug: 'moving-delivery',
    description: 'Furniture moving, heavy lifting, courier',
    icon: 'Truck',
    taskCount: 84,
  },
  {
    id: 'cat_gardening',
    name: 'Gardening & Outdoor',
    slug: 'gardening-outdoor',
    description: 'Lawn mowing, landscaping, patio care',
    icon: 'Flower2',
    taskCount: 63,
  },
  {
    id: 'cat_design',
    name: 'Design & Creative',
    slug: 'design-creative',
    description: 'Logo, interior design, photo & video',
    icon: 'Palette',
    taskCount: 112,
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task_001',
    title: 'Assemble IKEA PAX Wardrobe System & Wall Anchor',
    description:
      'Need an experienced handyman to assemble a 3-unit IKEA PAX wardrobe system with sliding doors and secure it to drywall studs. All tools provided if needed.',
    categoryId: 'cat_home',
    categoryName: 'Home Improvement',
    customerId: 'user_cust_101',
    customerName: 'Sarah Jenkins',
    customerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    providerId: 'user_prov_202',
    providerName: 'Alex Rivera',
    providerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    budget: 180,
    status: 'IN_PROGRESS',
    location: 'Austin, TX (Downtown)',
    isRemote: false,
    dueDate: '2026-09-15T18:00:00Z',
    createdAt: '2026-09-08T10:30:00Z',
    updatedAt: '2026-09-09T14:20:00Z',
    applicantsCount: 4,
    tags: ['Assembly', 'Furniture', 'IKEA', 'Handyman'],
  },
  {
    id: 'task_002',
    title: 'Custom React & Tailwind Component Library Refactoring',
    description:
      'Looking for a senior frontend developer to convert existing legacy CSS modules to clean Tailwind CSS utility components with TypeScript interfaces.',
    categoryId: 'cat_tech',
    categoryName: 'Tech & IT Support',
    customerId: 'user_cust_101',
    customerName: 'Sarah Jenkins',
    customerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    budget: 450,
    status: 'OPEN',
    location: 'Remote',
    isRemote: true,
    dueDate: '2026-09-20T23:59:00Z',
    createdAt: '2026-09-09T16:00:00Z',
    updatedAt: '2026-09-09T16:00:00Z',
    applicantsCount: 7,
    tags: ['React', 'TypeScript', 'Tailwind', 'Frontend'],
  },
  {
    id: 'task_003',
    title: 'Deep House Cleaning - 3 Bed, 2 Bath Residence',
    description:
      'Comprehensive deep cleaning including windows, kitchen appliances, oven interior, bathrooms, and hardwood floor conditioning.',
    categoryId: 'cat_cleaning',
    categoryName: 'Cleaning & Housekeeping',
    customerId: 'user_cust_101',
    customerName: 'Sarah Jenkins',
    customerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    providerId: 'user_prov_305',
    providerName: 'Maria Santos',
    providerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    budget: 220,
    status: 'COMPLETED',
    location: 'Austin, TX (South Congress)',
    isRemote: false,
    dueDate: '2026-09-05T15:00:00Z',
    createdAt: '2026-09-01T09:15:00Z',
    updatedAt: '2026-09-05T17:30:00Z',
    applicantsCount: 5,
    tags: ['Cleaning', 'Housekeeping', 'Deep Clean'],
  },
  {
    id: 'task_004',
    title: 'Modern Brand Identity & Vector Logo Design',
    description:
      'Create a minimalist, modern logo mark and brand color palette for a newly launching artisanal coffee brand.',
    categoryId: 'cat_design',
    categoryName: 'Design & Creative',
    customerId: 'user_cust_101',
    customerName: 'Sarah Jenkins',
    customerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    budget: 300,
    status: 'OPEN',
    location: 'Remote',
    isRemote: true,
    dueDate: '2026-09-25T18:00:00Z',
    createdAt: '2026-09-10T11:00:00Z',
    updatedAt: '2026-09-10T11:00:00Z',
    applicantsCount: 3,
    tags: ['Logo Design', 'Branding', 'Figma', 'Illustrator'],
  },
  {
    id: 'task_005',
    title: 'Backyard Sprinkler & Drip Irrigation Repair',
    description:
      'Fix 2 leaking sprinkler heads and program the digital controller timer for summer schedule.',
    categoryId: 'cat_gardening',
    categoryName: 'Gardening & Outdoor',
    customerId: 'user_cust_101',
    customerName: 'Sarah Jenkins',
    budget: 120,
    status: 'DRAFT',
    location: 'Austin, TX',
    isRemote: false,
    dueDate: '2026-09-18T17:00:00Z',
    createdAt: '2026-09-10T14:30:00Z',
    updatedAt: '2026-09-10T14:30:00Z',
    applicantsCount: 0,
    tags: ['Irrigation', 'Lawn Care', 'Repair'],
  },
];

export const mockProviders: Provider[] = [
  {
    id: 'prov_202',
    userId: 'user_prov_202',
    name: 'Alex Rivera',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    headline: 'Licensed General Contractor & Assembly Expert',
    bio: '10+ years experience in custom furniture assembly, wall mounting, electrical fixtures, and home maintenance.',
    rating: 4.95,
    reviewCount: 128,
    hourlyRate: 55,
    skills: ['IKEA Assembly', 'Carpentry', 'Electrical', 'Plumbing Repairs'],
    completedTasksCount: 142,
    verified: true,
    location: 'Austin, TX',
    available: true,
  },
  {
    id: 'prov_305',
    userId: 'user_prov_305',
    name: 'Maria Santos',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    headline: 'Eco-Friendly Residential & Commercial Specialist',
    bio: 'Detail-oriented professional cleaning team using non-toxic green certified solutions.',
    rating: 4.9,
    reviewCount: 94,
    hourlyRate: 45,
    skills: ['Deep Cleaning', 'Eco-Products', 'Organization', 'Move-out Clean'],
    completedTasksCount: 110,
    verified: true,
    location: 'Austin, TX',
    available: true,
  },
  {
    id: 'prov_401',
    userId: 'user_prov_401',
    name: 'David Chen',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    headline: 'Full-Stack Developer & UI Architect',
    bio: 'Ex-BigTech engineer specializing in React, Node, Tailwind, and scalable cloud solutions.',
    rating: 5.0,
    reviewCount: 67,
    hourlyRate: 85,
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Tailwind CSS'],
    completedTasksCount: 75,
    verified: true,
    location: 'Remote',
    available: true,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif_01',
    userId: 'user_cust_101',
    title: 'New Applicant on your task',
    message: 'David Chen applied for "Custom React & Tailwind Component Library Refactoring"',
    type: 'NEW_APPLICATION',
    isRead: false,
    createdAt: '2026-09-10T15:20:00Z',
    link: '/customer/tasks',
  },
  {
    id: 'notif_02',
    userId: 'user_cust_101',
    title: 'Task status updated',
    message: 'Alex Rivera updated status to "In Progress" for PAX Wardrobe Assembly',
    type: 'TASK_UPDATE',
    isRead: false,
    createdAt: '2026-09-09T14:20:00Z',
    link: '/customer/tasks',
  },
  {
    id: 'notif_03',
    userId: 'user_cust_101',
    title: 'Payment Escrow Confirmed',
    message: 'Payment of $220.00 released for Deep House Cleaning',
    type: 'PAYMENT_RECEIVED',
    isRead: true,
    createdAt: '2026-09-05T17:35:00Z',
    link: '/customer/dashboard',
  },
];

export const mockPayments: Payment[] = [
  {
    id: 'pay_1001',
    taskId: 'task_003',
    taskTitle: 'Deep House Cleaning - 3 Bed, 2 Bath Residence',
    customerId: 'user_cust_101',
    providerId: 'user_prov_305',
    amount: 220,
    fee: 11,
    totalAmount: 231,
    status: 'RELEASED',
    paymentMethod: 'Visa ending in 4242',
    createdAt: '2026-09-05T17:30:00Z',
    transactionRef: 'txn_987654321',
  },
  {
    id: 'pay_1002',
    taskId: 'task_001',
    taskTitle: 'Assemble IKEA PAX Wardrobe System & Wall Anchor',
    customerId: 'user_cust_101',
    providerId: 'user_prov_202',
    amount: 180,
    fee: 9,
    totalAmount: 189,
    status: 'HELD_IN_ESCROW',
    paymentMethod: 'Mastercard ending in 8812',
    createdAt: '2026-09-08T10:35:00Z',
    transactionRef: 'txn_123456789',
  },
];
